dist: ubuntu
sudo: required
language: node_js
node_js:
  - 10

git:
  depth: false


branches:
  only:
    - dev
    - master

install:
  - curl -sf https://up.apex.sh/install | sudo sh

stages:
  - dev
  - production

jobs:
  include:
  - stage : dev
    if: branch = "dev" 
    env:
      - STAGE=dev
    deploy:
      provider: script
      script:
        yarn;
        up deploy $STAGE;
      on:
        branch: dev
  
  - stage: production
    if: branch = "master"
    env:
      - STAGE=production
    deploy:
      provider: script
      script:
        yarn;
        up deploy $STAGE;
      on:
        branch: master

