sudo: required
language: node_js

node_js:
  - 10
  - 9
os:
  - linux
  - osx

branches:
  only:
    - matrix


jobs:
  include:
   - node_js: 10
     os: linux
     script:
        echo "hello world from the node-10 and linux"
   - node_js: 9
     os: osx
     script:
        echo "hello world from the node-9 and apple"  
