language: node_js
node_js:
  - 10

stage:
  - dev
  - prod

branches:
  only:
    - stages

jobs:
  include:
    - stage: dev
      name: test1
      script:
        echo "hello world from dev1"
      name: test2
      script:
        echo "hello world  from dev2"
    
    - stage: prod
      name: test1
      script:
        echo "hello world from prod1"
      name: test2
      script:
        echo "hello world  from prod2"