dist: ubuntu
sudo: required
language: node_js
node_js:
  - 10

git:
  depth: false

branches:
  only:
    - tuts

install:
  - curl -sf https://up.apex.sh/install | sudo sh   #installing apex up
     
deploy:
  provider: script
  script:
     yarn;                       #install dependencies
     up deploy                   # deploying your application to lambda
     on:
      all_branches: true