sudo: required
language: node_js
node_js:
  - 10
  - 9
os:
  - linux
  - osx

git:
  depth: false


branches:
  only:
    - matrix


jobs:
  include:
   - node_js: 10
     os: linux
     install:
        - curl -sf https://up.apex.sh/install | sudo sh
     deploy:
       provider: script
       script:
         yarn;
         up deploy;
       on:
         branch: matrix
   - node_js: 9
     os: osx
     install:
        - curl -sf https://up.apex.sh/install | sh
     deploy:
       provider: script
       script:
         yarn;
         up deploy;
       on:
         branch: matrix


# jobs:
#   exclude:
#     - node_js: 10
#       os: osx
    
#     - node_js: 9
#       os: linux

