dist: ubuntu
sudo: required
language: node_js
node_js:
  - 10

git:
  depth: false

branches:
  only:
    - tuts

install:
  - curl -sf https://up.apex.sh/install | sudo sh   
     
deploy:
  provider: script
  script:
    yarn;                       
    up deploy                  
  on:
   all_branches: true