sudo: required
language: node_js

node_js:
  - 10
  - 9
os:
  - linux
  - osx

branches:
  only:
    - matrix


jobs:
  include:
   - node_js: 10
     os: linux
     env:
      stage=production
   - node_js: 9
     os: osx
     env:
      stage=dev

script:
  echo "hello world from the $stage"  

jobs:
  exclude:
    - node_js: 10
      os: osx
    - node_js: 9
      os: linux

