sudo: required
language: node_js
node_js:
  - 10
  - 9
os:
  - linux
  - osx

git:
  depth: false


branches:
  only:
    - matrix

install:
  - curl -sf https://up.apex.sh/install | sudo sh



jobs:
  include:
   - node_js: 10
     os: linux
     deploy:
       provider: script
       script:
         yarn;
         up deploy;
       on:
         branch: matrix
   - node_js: 9
     os: osx
     deploy:
       provider: script
       script:
         yarn;
         up deploy;
       on:
         branch: matrix
  
  exclude:
    - node_js: 10
      os: osx
    
    - node_js: 9
      os: linux

